<?php

namespace ContainerVpbTQUu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeDrinkCommandService extends GetWith_CoffeeMachine_KernelXtrDebugContainer
{
    /**
     * Gets the private 'GetWith\CoffeeMachine\UI\Command\MakeDrinkCommand' shared autowired service.
     *
     * @return \GetWith\CoffeeMachine\UI\Command\MakeDrinkCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Command/MakeDrinkCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Application/OrderDrinkService.php';
        include_once \dirname(__DIR__, 4) . '/src/Domain/Repository/CoffeeRepository.php';
        include_once \dirname(__DIR__, 4) . '/src/Infrastructure/CoffeeRepositoryImpl.php';

        $container->privates['GetWith\\CoffeeMachine\\UI\\Command\\MakeDrinkCommand'] = $instance = new \GetWith\CoffeeMachine\UI\Command\MakeDrinkCommand(new \GetWith\CoffeeMachine\Application\OrderDrinkService(new \GetWith\CoffeeMachine\Infrastructure\CoffeeRepositoryImpl()));

        $instance->setName('app:order-drink');

        return $instance;
    }
}
